apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app

spec:
<<<<<<< HEAD
  replicas: 1         # if write 3 it will create 3 replicas
=======
  replicas: 3          # if write 3 it will create 3 replicas
>>>>>>> 4d11726b23c4e36f8efd4a64180c62ead034e905
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app-cntr
          image: imdaquib/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: "mysql"                     # service cluster IP
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always